name: Android Build CI

on: [workflow_dispatch] 

jobs:
  build-main:
    name: Android
    runs-on: ubuntu-${{ matrix.version }}
    strategy:
      matrix:
        arch: [arm64, armv7, 32]
        build: [release]
        version: [20.04]
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Android NDK
        uses: nttld/setup-ndk@main
        id: setup-ndk
        with:
          ndk-version: r11c
      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          distribution: zulu
          java-version: 11
      - name: Setup Android SDK
        uses: android-actions/setup-android@main
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.1.5
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install lime 7.9.0 --quiet
          haxelib install hxcpp 4.2.1 --quiet
          haxelib install openfl 9.1.0 --quiet
          haxelib install actuate 1.8.9 --quiet
          haxelib --never install flixel 4.9.0 --quiet
          haxelib install flixel-ui 2.3.3 --quiet
          haxelib install hscript 2.4.0 --quiet
          haxelib install flixel-addons 2.10.0 --quiet
          haxelib git linc_luajit https://github.com/sirox228/linc_luajit.git
          haxelib git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools.git
          haxelib git extension-videoview https://github.com/mcagabe19-stuff/extension-videoview.git
      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: Compile
        run: haxelib run lime build android -D mobileC -D NO_PRECOMPILED_HEADERS -${{ matrix.build }} -${{ matrix.arch }}
        env:
          cert_pass: 123456
          cert_alias_pass: 123456
      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: build-ubuntu${{ matrix.version }}-${{ matrix.arch }}-${{ matrix.build }}
          path: 'export/${{ matrix.build }}/android/bin/app/build/outputs/apk/${{ matrix.build }}/*.apk'
  build-armv6:
    name: Android
    runs-on: ubuntu-${{ matrix.version }}
    strategy:
      matrix:
        arch: [armv6]
        build: [release]
        version: [20.04]
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Android NDK
        uses: nttld/setup-ndk@main
        id: setup-ndk
        with:
          ndk-version: r11c
      - name: Setup Java JDK
        uses: actions/setup-java@main
        with:
          distribution: zulu
          java-version: 11
      - name: Setup Android SDK
        uses: android-actions/setup-android@main
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.1.5
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install lime 7.9.0 --quiet
          haxelib install hxcpp 4.2.1 --quiet
          haxelib install openfl 9.1.0 --quiet
          haxelib install actuate 1.8.9 --quiet
          haxelib --never git flixel https://github.com/mcagabe19/flixel-4.9.0.git
          haxelib install flixel-ui 2.3.3 --quiet
          haxelib install hscript 2.4.0 --quiet
          haxelib install flixel-addons 2.10.0 --quiet
          haxelib git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools.git
          haxelib git extension-videoview https://github.com/MAJigsaw77/extension-videoview.git
      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: Compile
        run: haxelib run lime build android -D nolua -D mobileC -D NO_PRECOMPILED_HEADERS -${{ matrix.build }} -${{ matrix.arch }}
        env:
          cert_pass: 123456
          cert_alias_pass: 123456
      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: build-ubuntu${{ matrix.version }}-${{ matrix.arch }}-${{ matrix.build }}
          path: 'export/${{ matrix.build }}/android/bin/app/build/outputs/apk/${{ matrix.build }}/*.apk'
