name: Mac Build CI

on: [workflow_dispatch]

jobs:
  build-64:
    name: MacOS64
    runs-on: macos-${{ matrix.version }}
    strategy:
      matrix:
        build: [release]
        version: [11, 12]
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.1.5
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install lime 7.9.0 --quiet
          haxelib git hxcpp https://github.com/mcagabe19/hxcpp-fastspeed.git
          haxelib install openfl 9.1.0 --quiet
          haxelib install actuate 1.8.9 --quiet
          haxelib --never git flixel https://github.com/mcagabe19/flixel-4.9.0.git
          haxelib install flixel-ui 2.3.3 --quiet
          haxelib install hscript 2.4.0 --quiet
          haxelib install flixel-addons 2.10.0 --quiet
          haxelib git linc_luajit https://github.com/sirox228/linc_luajit.git
      - name: Compile
        run: haxelib run lime build mac -64 -${{ matrix.build }} -D no-compilation -D macro-times -D analyzer-optimize
      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: build-macos${{ matrix.version }}-64-${{ matrix.build }}
          path: 'export/${{ matrix.build }}/macos/bin'
